name: preprocess
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.17=h5eee18b_0
  - packaging=25.0=py310h06a4308_1
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.10.2=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.46.3=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
    - anyio==4.12.1
    - certifi==2026.1.4
    - charset-normalizer==3.4.4
    - click==8.3.1
    - datasets==4.5.0
    - dill==0.4.1
    - exceptiongroup==1.3.1
    - filelock==3.20.3
    - fsspec==2025.10.0
    - h11==0.16.0
    - hf-xet==1.2.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==1.4.1
    - idna==3.11
    - multiprocess==0.70.18
    - numpy==2.2.6
    - pandas==2.3.2
    - pillow==12.1.0
    - pyarrow==20.0.0
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyyaml==6.0.3
    - requests==2.32.5
    - shellingham==1.5.4
    - six==1.17.0
    - tqdm==4.67.3
    - typer-slim==0.21.1
    - typing-extensions==4.15.0
    - tzdata==2025.3
    - urllib3==2.6.3
    - xxhash==3.6.0
prefix: /mnt/petrelfs/wangxuanxu/miniconda3/envs/preprocess
